### ISSUE TITLE
Activity provider registration schema failure

### ISSUE THREAD

**Issue by fsgeek** [ubc-systopia/Indaleko#65]
Traceback (most recent call last):
  File "C:\Users\TonyMason\source\repos\indaleko\activity\collectors\location\windows_gps_location.py", line 188, in <module>
    main()
  File "C:\Users\TonyMason\source\repos\indaleko\activity\collectors\location\windows_gps_location.py", line 180, in main
    collector = WindowsGPSLocationCollector()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\source\repos\indaleko\activity\collectors\location\windows_gps_location.py", line 97, in __init__
    provider_data, collection = self.provider_registrar.register_provider(**record_kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\source\repos\indaleko\activity\provider_registration_service.py", line 261, in register_provider
    insert(json.dumps(activity_registration_data, default=str))
  File "C:\Users\TonyMason\source\repos\indaleko\IndalekoCollection.py", line 123, in insert
    return self.collection.insert(document, overwrite=overwrite)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\collection.py", line 2615, in insert
    return self._execute(request, response_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\executor.py", line 66, in execute
    return response_handler(resp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\collection.py", line 2605, in response_handler
    raise DocumentInsertError(resp, request)
arango.exceptions.DocumentInsertError: [HTTP 400][ERR 1620] schema validation failed

As I recall, there's an issue with the schema that gets written into the services collection.  This should be resolved so the schema is correctly configured.

**Comment by fsgeek** [comment]
Here's the schema that I see the code is using (activity_data_provider_registration.py):

{
    "$defs": {
        "IndalekoRecordDataModel": {
            "description": "This class defines the UUID data model for Indaleko.",
            "example": {
                "Attributes": {
                    "Indexer": "0793b4d5-e549-4cb6-8177-020a738b66b7",
                    "Name": "rufus-4.1.exe",
                    "ObjectIdentifier": "2c73d6e5-eaba-4f0a-acf3-e02c529f097a",
                    "Path": "d:\\dist",
                    "URI": "\\\\?\\Volume{3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c}\\dist\\rufus-4.1.exe",
                    "Volume GUID": "3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c",
                    "st_atime": 1693223456.3334281,
                    "st_atime_ns": 1693223456333428100,
                    "st_birthtime": 1685891221.5591917,
                    "st_birthtime_ns": 1685891221559191700,
                    "st_ctime": 1685891221.5591917,
                    "st_ctime_ns": 1685891221559191700,
                    "st_dev": 2756347094955649599,
                    "st_file_attributes": 32,
                    "st_gid": 0,
                    "st_ino": 1125899910119832,
                    "st_mode": 33279,
                    "st_mtime": 1685891221.5597157,
                    "st_mtime_ns": 1685891221559715700,
                    "st_nlink": 1,
                    "st_reparse_tag": 0,
                    "st_size": 1410120,
                    "st_uid": 0
                },
                "Data": "xQL6xQL3eyJzdF9hdGltZSI6IDE2OTMyMjM0NTYuMzMzNDI4MSwgInN0X2F0aW1lX25zIjogMTY5MzIyMzQ1NjMzMzQyODEwMCwgInN0X2JpcnRodGltZSI6IDE2ODU4OTEyMjEuNTU5MTkxNywgInN0X2JpcnRodGltZV9ucyI6IDE2ODU4O
TEyMjE1NTkxOTE3MDAsICJzdF9jdGltZSI6IDE2ODU4OTEyMjEuNTU5MTkxNywgInN0X2N0aW1lX25zIjogMTY4NTg5MTIyMTU1OTE5MTcwMCwgInN0X2RldiI6IDI3NTYzNDcwOTQ5NTU2NDk1OTksICJzdF9maWxlX2F0dHJpYnV0ZXMiOiAzMiwgInN0X2dpZCI6IDAsICJ
zdF9pbm8iOiAxMTI1ODk5OTEwMTE5ODMyLCAic3RfbW9kZSI6IDMzMjc5LCAic3RfbXRpbWUiOiAxNjg1ODkxMjIxLjU1OTcxNTcsICJzdF9tdGltZV9ucyI6IDE2ODU4OTEyMjE1NTk3MTU3MDAsICJzdF9ubGluayI6IDEsICJzdF9yZXBhcnNlX3RhZyI6IDAsICJzdF9za
XplIjogMTQxMDEyMCwgInN0X3VpZCI6IDAsICJOYW1lIjogInJ1ZnVzLTQuMS5leGUiLCAiUGF0aCI6ICJkOlxcZGlzdCIsICJVUkkiOiAiXFxcXD9cXFZvbHVtZXszMzk3ZDk3Yi0yY2E1LTExZWQtYjJmYy1iNDBlZGU5YTVhM2N9XFxkaXN0XFxydWZ1cy00LjEuZXhlIiw
gIkluZGV4ZXIiOiAiMDc5M2I0ZDUtZTU0OS00Y2I2LTgxNzctMDIwYTczOGI2NmI3IiwgIlZvbHVtZSBHVUlEIjogIjMzOTdkOTdiLTJjYTUtMTFlZC1iMmZjLWI0MGVkZTlhNWEzYyIsICJPYmplY3RJZGVudGlmaWVyIjogIjJjNzNkNmU1LWVhYmEtNGYwYS1hY2YzLWUwM
mM1MjlmMDk3YSJ9",
                "SourceIdentifier": {
                    "Identifier": "429f1f3c-7a21-463f-b7aa-cd731bb202b1",
                    "Version": "1.0"
                },
                "Timestamp": "2024-07-30T23:38:48.319654+00:00"
            },
            "properties": {
                "SourceIdentifier": {
                    "allOf": [
                        {
                            "$ref": "#/$defs/IndalekoSourceIdentifierDataModel"
                        }
                    ],
                    "description": "The source identifier for the record.",
                    "title": "SourceIdentifier"
                },
                "Timestamp": {
                    "description": "The timestamp of when this record was created.",
                    "format": "date-time",
                    "title": "Timestamp",
                    "type": "string"
                },
                "Attributes": {
                    "description": "The attributes extracted from the source data.",
                    "title": "Attributes",
                    "type": "object"
                },
                "Data": {
                    "description": "The raw (uninterpreted) data from the source.",
                    "title": "Data",
                    "type": "string"
                }
            },
            "required": [
                "SourceIdentifier",
                "Timestamp",
                "Attributes",
                "Data"
            ],
            "title": "IndalekoRecordDataModel",
            "type": "object"
        },
        "IndalekoSourceIdentifierDataModel": {
            "description": "This class defines the UUID data model for Indaleko.",
            "example": {
                "Description": "This is a sample IndalekoSourceIdentifierDataModel.",
                "Identifier": "12345678-1234-5678-1234-567812345678",
                "Version": "3.1"
            },
            "properties": {
                "Identifier": {
                    "description": "The UUID for the record.",
                    "example": "12345678-1234-5678-1234-567812345678",
                    "format": "uuid",
                    "title": "Identifier",
                    "type": "string"
                },
                "Version": {
                    "description": "The version of the source identifier.",
                    "example": "3.1",
                    "title": "Version",
                    "type": "string"
                },
                "Description": {
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "default": null,
                    "description": "A human-readable description of the data source.",
                    "example": "This is a sample IndalekoSourceIdentifierDataModel.",
                    "title": "Description"
                }
            },
            "required": [
                "Identifier",
                "Version"
            ],
            "title": "IndalekoSourceIdentifierDataModel",
            "type": "object"
        }
    },
    "description": "This class defines the activity data provider registration for the\nIndaleko system.",
    "example": {
        "Description": "This is a sample activity data provider registration.",
        "Identifier": "429f1f3c-7a21-463f-b7aa-cd731bb202b1",
        "Record": {
            "Attributes": {
                "Indexer": "0793b4d5-e549-4cb6-8177-020a738b66b7",
                "Name": "rufus-4.1.exe",
                "ObjectIdentifier": "2c73d6e5-eaba-4f0a-acf3-e02c529f097a",
                "Path": "d:\\dist",
                "URI": "\\\\?\\Volume{3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c}\\dist\\rufus-4.1.exe",
                "Volume GUID": "3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c",
                "st_atime": 1693223456.3334281,
                "st_atime_ns": 1693223456333428100,
                "st_birthtime": 1685891221.5591917,
                "st_birthtime_ns": 1685891221559191700,
                "st_ctime": 1685891221.5591917,
                "st_ctime_ns": 1685891221559191700,
                "st_dev": 2756347094955649599,
                "st_file_attributes": 32,
                "st_gid": 0,
                "st_ino": 1125899910119832,
                "st_mode": 33279,
                "st_mtime": 1685891221.5597157,
                "st_mtime_ns": 1685891221559715700,
                "st_nlink": 1,
                "st_reparse_tag": 0,
                "st_size": 1410120,
                "st_uid": 0
            },
            "Data": "xQL6xQL3eyJzdF9hdGltZSI6IDE2OTMyMjM0NTYuMzMzNDI4MSwgInN0X2F0aW1lX25zIjogMTY5MzIyMzQ1NjMzMzQyODEwMCwgInN0X2JpcnRodGltZSI6IDE2ODU4OTEyMjEuNTU5MTkxNywgInN0X2JpcnRodGltZV9ucyI6IDE2ODU4OTEyM
jE1NTkxOTE3MDAsICJzdF9jdGltZSI6IDE2ODU4OTEyMjEuNTU5MTkxNywgInN0X2N0aW1lX25zIjogMTY4NTg5MTIyMTU1OTE5MTcwMCwgInN0X2RldiI6IDI3NTYzNDcwOTQ5NTU2NDk1OTksICJzdF9maWxlX2F0dHJpYnV0ZXMiOiAzMiwgInN0X2dpZCI6IDAsICJzdF9
pbm8iOiAxMTI1ODk5OTEwMTE5ODMyLCAic3RfbW9kZSI6IDMzMjc5LCAic3RfbXRpbWUiOiAxNjg1ODkxMjIxLjU1OTcxNTcsICJzdF9tdGltZV9ucyI6IDE2ODU4OTEyMjE1NTk3MTU3MDAsICJzdF9ubGluayI6IDEsICJzdF9yZXBhcnNlX3RhZyI6IDAsICJzdF9zaXplI
jogMTQxMDEyMCwgInN0X3VpZCI6IDAsICJOYW1lIjogInJ1ZnVzLTQuMS5leGUiLCAiUGF0aCI6ICJkOlxcZGlzdCIsICJVUkkiOiAiXFxcXD9cXFZvbHVtZXszMzk3ZDk3Yi0yY2E1LTExZWQtYjJmYy1iNDBlZGU5YTVhM2N9XFxkaXN0XFxydWZ1cy00LjEuZXhlIiwgIkl
uZGV4ZXIiOiAiMDc5M2I0ZDUtZTU0OS00Y2I2LTgxNzctMDIwYTczOGI2NmI3IiwgIlZvbHVtZSBHVUlEIjogIjMzOTdkOTdiLTJjYTUtMTFlZC1iMmZjLWI0MGVkZTlhNWEzYyIsICJPYmplY3RJZGVudGlmaWVyIjogIjJjNzNkNmU1LWVhYmEtNGYwYS1hY2YzLWUwMmM1M
jlmMDk3YSJ9",
            "SourceIdentifier": {
                "Identifier": "429f1f3c-7a21-463f-b7aa-cd731bb202b1",
                "Version": "1.0"
            },
            "Timestamp": "2024-07-30T23:38:48.319654+00:00"
        },
        "Version": "1.0"
    },
    "properties": {
        "Identifier": {
            "description": "The UUID for the activity data provider.",
            "format": "uuid",
            "title": "Identifier",
            "type": "string"
        },
        "Version": {
            "description": "The version of the activity data provider.",
            "title": "Version",
            "type": "string"
        },
        "Description": {
            "description": "A description of the activity data provider.",
            "title": "Description",
            "type": "string"
        },
        "Record": {
            "allOf": [
                {
                    "$ref": "#/$defs/IndalekoRecordDataModel"
                }
            ],
            "description": "Standard data record format.",
            "title": "Record"
        }
    },
    "required": [
        "Identifier",
        "Version",
        "Description",
        "Record"
    ],
    "title": "IndalekoActivityDataProviderRegistrationDataModel",
    "type": "object"
}

This is definitely not what is in the database.

**Comment by fsgeek** [comment]
The correct schema (the one emitted by the data model) does work:

{
    "message": "",
    "level": "strict",
    "type": "json",
    "rule": {
        "$defs": {
            "IndalekoRecordDataModel": {
                "description": "This class defines the UUID data model for Indaleko.",
                "example": {
                    "Attributes": {
                        "Indexer": "0793b4d5-e549-4cb6-8177-020a738b66b7",
                        "Name": "rufus-4.1.exe",
                        "ObjectIdentifier": "2c73d6e5-eaba-4f0a-acf3-e02c529f097a",
                        "Path": "d:\\dist",
                        "URI": "\\\\?\\Volume{3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c}\\dist\\rufus-4.1.exe",
                        "Volume GUID": "3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c",
                        "st_atime": 1693223456.3334281,
                        "st_atime_ns": 1693223456333428100,
                        "st_birthtime": 1685891221.5591917,
                        "st_birthtime_ns": 1685891221559191700,
                        "st_ctime": 1685891221.5591917,
                        "st_ctime_ns": 1685891221559191700,
                        "st_dev": 2756347094955649599,
                        "st_file_attributes": 32,
                        "st_gid": 0,
                        "st_ino": 1125899910119832,
                        "st_mode": 33279,
                        "st_mtime": 1685891221.5597157,
                        "st_mtime_ns": 1685891221559715700,
                        "st_nlink": 1,
                        "st_reparse_tag": 0,
                        "st_size": 1410120,
                        "st_uid": 0
                    },
                    "Data": "",
                    "SourceIdentifier": {
                        "Identifier": "429f1f3c-7a21-463f-b7aa-cd731bb202b1",
                        "Version": "1.0"
                    },
                    "Timestamp": "2024-07-30T23:38:48.319654+00:00"
                },
                "properties": {
                    "SourceIdentifier": {
                        "allOf": [
                            {
                                "$ref": "#/$defs/IndalekoSourceIdentifierDataModel"
                            }
                        ],
                        "description": "The source identifier for the record.",
                        "title": "SourceIdentifier"
                    },
                    "Timestamp": {
                        "description": "The timestamp of when this record was created.",
                        "format": "date-time",
                        "title": "Timestamp",
                        "type": "string"
                    },
                    "Attributes": {
                        "description": "The attributes extracted from the source data.",
                        "title": "Attributes",
                        "type": "object"
                    },
                    "Data": {
                        "description": "The raw (uninterpreted) data from the source.",
                        "title": "Data",
                        "type": "string"
                    }
                },
                "required": [
                    "SourceIdentifier",
                    "Timestamp",
                    "Attributes",
                    "Data"
                ],
                "title": "IndalekoRecordDataModel",
                "type": "object"
            },
            "IndalekoSourceIdentifierDataModel": {
                "description": "This class defines the UUID data model for Indaleko.",
                "example": {
                    "Description": "This is a sample IndalekoSourceIdentifierDataModel.",
                    "Identifier": "12345678-1234-5678-1234-567812345678",
                    "Version": "3.1"
                },
                "properties": {
                    "Identifier": {
                        "description": "The UUID for the record.",
                        "example": "12345678-1234-5678-1234-567812345678",
                        "format": "uuid",
                        "title": "Identifier",
                        "type": "string"
                    },
                    "Version": {
                        "description": "The version of the source identifier.",
                        "example": "3.1",
                        "title": "Version",
                        "type": "string"
                    },
                    "Description": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "default": null,
                        "description": "A human-readable description of the data source.",
                        "example": "This is a sample IndalekoSourceIdentifierDataModel.",
                        "title": "Description"
                    }
                },
                "required": [
                    "Identifier",
                    "Version"
                ],
                "title": "IndalekoSourceIdentifierDataModel",
                "type": "object"
            }
        },
        "description": "This class defines the activity data provider registration for the\nIndaleko system.",
        "example": {
            "Description": "This is a sample activity data provider registration.",
            "Identifier": "429f1f3c-7a21-463f-b7aa-cd731bb202b1",
            "Record": {
                "Attributes": {
                    "Indexer": "0793b4d5-e549-4cb6-8177-020a738b66b7",
                    "Name": "rufus-4.1.exe",
                    "ObjectIdentifier": "2c73d6e5-eaba-4f0a-acf3-e02c529f097a",
                    "Path": "d:\\dist",
                    "URI": "\\\\?\\Volume{3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c}\\dist\\rufus-4.1.exe",
                    "Volume GUID": "3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c",
                    "st_atime": 1693223456.3334281,
                    "st_atime_ns": 1693223456333428100,
                    "st_birthtime": 1685891221.5591917,
                    "st_birthtime_ns": 1685891221559191700,
                    "st_ctime": 1685891221.5591917,
                    "st_ctime_ns": 1685891221559191700,
                    "st_dev": 2756347094955649599,
                    "st_file_attributes": 32,
                    "st_gid": 0,
                    "st_ino": 1125899910119832,
                    "st_mode": 33279,
                    "st_mtime": 1685891221.5597157,
                    "st_mtime_ns": 1685891221559715700,
                    "st_nlink": 1,
                    "st_reparse_tag": 0,
                    "st_size": 1410120,
                    "st_uid": 0
                },
                "Data": "",
                "SourceIdentifier": {
                    "Identifier": "429f1f3c-7a21-463f-b7aa-cd731bb202b1",
                    "Version": "1.0"
                },
                "Timestamp": "2024-07-30T23:38:48.319654+00:00"
            },
            "Version": "1.0"
        },
        "properties": {
            "Identifier": {
                "description": "The UUID for the activity data provider.",
                "format": "uuid",
                "title": "Identifier",
                "type": "string"
            },
            "Version": {
                "description": "The version of the activity data provider.",
                "title": "Version",
                "type": "string"
            },
            "Description": {
                "description": "A description of the activity data provider.",
                "title": "Description",
                "type": "string"
            },
            "Record": {
                "allOf": [
                    {
                        "$ref": "#/$defs/IndalekoRecordDataModel"
                    }
                ],
                "description": "Standard data record format.",
                "title": "Record"
            }
        },
        "required": [
            "Identifier",
            "Version",
            "Description",
            "Record"
        ],
        "title": "IndalekoActivityDataProviderRegistrationDataModel",
        "type": "object"
    }
}


Thus, it looks like the issue is that the collection is being created with the wrong schema.

**Comment by fsgeek** [comment]
So, this relates to the move to push activity data handling into the "activity" sub-module.  This was using the older data definition.  To "fix this" Indaleko.py needs to reference the correct data model and return the correct schema.  

In addition, the code that is still at top level is deprecated and should be removed, to avoid any additional confusion.

For a "small bug" this is an extensive change.

**Comment by fsgeek** [comment]
Addressed quite a few issues in commit 2e2f3bd140ff87bc70be65c7ace1327dd29c5c76.  Decided to check in these changes (preliminarily) because I have to reset the database and ensure the schema are being properly built to confirm the work is complete.  Unfortunately, it is not.

Traceback (most recent call last):
  File "C:\Users\TonyMason\source\repos\indaleko\activity\recorders\location\windows_gps_location.py", line 190, in <module>
    main()
  File "C:\Users\TonyMason\source\repos\indaleko\activity\recorders\location\windows_gps_location.py", line 182, in main
    collector = WindowsGPSLocationCollector()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\source\repos\indaleko\activity\recorders\location\windows_gps_location.py", line 94, in __init__
    self.provider_registrar = IndalekoActivityDataRegistrationService()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\source\repos\indaleko\activity\recorders\registration_service.py", line 74, in __init__
    self.activity_provider_collection = IndalekoCollections().get_collection(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\source\repos\indaleko\IndalekoCollections.py", line 67, in __init__
    raise error
  File "C:\Users\TonyMason\source\repos\indaleko\IndalekoCollections.py", line 56, in __init__
    self.collections[name] = IndalekoCollection(name=name,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\source\repos\indaleko\IndalekoCollection.py", line 62, in __init__
    self.create_collection(self.collection_name, self.definition, reset=self.reset)
  File "C:\Users\TonyMason\source\repos\indaleko\IndalekoCollection.py", line 85, in create_collection
    raise error
  File "C:\Users\TonyMason\source\repos\indaleko\IndalekoCollection.py", line 79, in create_collection
    self.collection.configure(schema=config['schema'])
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\collection.py", line 419, in configure
    return self._execute(request, response_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\executor.py", line 66, in execute
    return response_handler(resp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TonyMason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\arango\collection.py", line 416, in response_handler
    raise CollectionConfigureError(resp, request)
arango.exceptions.CollectionConfigureError: [HTTP 400][ERR 1621] Error when building schema: No valid schema in rule attribute given (no object): {"Identifier":"429f1f3c-7a21-463f-b7aa-cd731bb202b1","Versio
n":"1.0","Description":"This is a sample activity data provider registration.","Record":{"SourceIdentifier":{"Identifier":"429f1f3c-7a21-463f-b7aa-cd731bb202b1","Version":"1.0","Description":null},"Timestam
p":"2024-07-30T23:38:48.319654Z","Attributes":{"st_atime":1.6932234563334281e+9,"st_atime_ns":1693223456333428100,"st_birthtime":1.6858912215591917e+9,"st_birthtime_ns":1685891221559191700,"st_ctime":1.6858
912215591917e+9,"st_ctime_ns":1685891221559191700,"st_dev":2756347094955649599,"st_file_attributes":32,"st_gid":0,"st_ino":1125899910119832,"st_mode":33279,"st_mtime":1.6858912215597157e+9,"st_mtime_ns":168
5891221559715700,"st_nlink":1,"st_reparse_tag":0,"st_size":1410120,"st_uid":0,"Name":"rufus-4.1.exe","Path":"d:\\dist","URI":"\\\\?\\Volume{3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c}\\dist\\rufus-4.1.exe","Index
er":"0793b4d5-e549-4cb6-8177-020a738b66b7","Volume GUID":"3397d97b-2ca5-11ed-b2fc-b40ede9a5a3c","ObjectIdentifier":"2c73d6e5-eaba-4f0a-acf3-e02c529f097a"},"Data":"xQL6xQL3eyJzdF9hdGltZSI6IDE2OTMyMjM0NTYuMzM
zNDI4MSwgInN0X2F0aW1lX25zIjogMTY5MzIyMzQ1NjMzMzQyODEwMCwgInN0X2JpcnRodGltZSI6IDE2ODU4OTEyMjEuNTU5MTkxNywgInN0X2JpcnRodGltZV9ucyI6IDE2ODU4OTEyMjE1NTkxOTE3MDAsICJzdF9jdGltZSI6IDE2ODU4OTEyMjEuNTU5MTkxNywgInN0X
2N0aW1lX25zIjogMTY4NTg5MTIyMTU1OTE5MTcwMCwgInN0X2RldiI6IDI3NTYzNDcwOTQ5NTU2NDk1OTksICJzdF9maWxlX2F0dHJpYnV0ZXMiOiAzMiwgInN0X2dpZCI6IDAsICJzdF9pbm8iOiAxMTI1ODk5OTEwMTE5ODMyLCAic3RfbW9kZSI6IDMzMjc5LCAic3RfbXR
pbWUiOiAxNjg1ODkxMjIxLjU1OTcxNTcsICJzdF9tdGltZV9ucyI6IDE2ODU4OTEyMjE1NTk3MTU3MDAsICJzdF9ubGluayI6IDEsICJzdF9yZXBhcnNlX3RhZyI6IDAsICJzdF9zaXplIjogMTQxMDEyMCwgInN0X3VpZCI6IDAsICJOYW1lIjogInJ1ZnVzLTQuMS5leGUiL
CAiUGF0aCI6ICJkOlxcZGlzdCIsICJVUkkiOiAiXFxcXD9cXFZvbHVtZXszMzk3ZDk3Yi0yY2E1LTExZWQtYjJmYy1iNDBlZGU5YTVhM2N9XFxkaXN0XFxydWZ1cy00LjEuZXhlIiwgIkluZGV4ZXIiOiAiMDc5M2I0ZDUtZTU0OS00Y2I2LTgxNzctMDIwYTczOGI2NmI3Iiw
gIlZvbHVtZSBHVUlEIjogIjMzOTdkOTdiLTJjYTUtMTFlZC1iMmZjLWI0MGVkZTlhNWEzYyIsICJPYmplY3RJZGVudGlmaWVyIjogIjJjNzNkNmU1LWVhYmEtNGYwYS1hY2YzLWUwMmM1MjlmMDk3YSJ9"}}

To produce this, I ran the windows gps location activity data tool, which caused creation of the collections, indices, and schema needed.  The service registration collection is not being created correctly because there is something wrong with the schema.  Thus, the original issue (which was schema rejection and identification it was incorrect) has not materially changed, but the manifestation is different.

**Comment by fsgeek** [comment]
Actually, it's not the services collection.  There was more debug output earlier in the display:

ERROR:root:Failed to configure collection ActivityDataProviders
Failed to configure collection ActivityDataProviders

This would not be from the original issue, but instead is likely related to the extensive set of changes I introduced to "clean things up".

**Comment by fsgeek** [comment]
Hopefully the last round of changes.  Commit 4285f605b7361a5ebd5204dfdfe56793dbc8e55f includes a shift to using a pydantic datatype that requires a timezone indicator.

THAT was the reason that service registration stopped working.
